version: '3'  
  
services:  
  presenton:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
    volumes:  
      - ./user_data:/app/user_data  
    environment:  
      - APP_DATA_DIRECTORY=/app/user_data
      - USER_CONFIG_PATH=/app/user_data/userConfig.json