services:  
  presenton:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "3000:3000"
      - "8000:8000"
    volumes:  
      - ./user_data:/app/user_data
    environment:
      - TEMP_DIRECTORY=/tmp/presenton
      - APP_DATA_DIRECTORY=/app/user_data