services:  
  presenton:  
    # image: ghcr.io/presenton/presenton:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTAPI_URL=${FASTAPI_URL:-http://0.0.0.0:8000}
    environment:
      - FASTAPI_URL=${FASTAPI_URL:-http://0.0.0.0:8000}
    ports:  
      - "3000:3000"
      - "8000:8000"
    volumes:  
      - ./user_data:/app/user_data

